from pathlib import Path

DEFAULT_MAX_FRAMES = 30

MAX_NUM_HANDS = 2
MIN_DETECTION_CONFIDENCE = 0.5
MIN_TRACKING_CONFIDENCE = 0.5

FEATURES_PER_FRAME = 2 * 21 * 3

CONFIDENCE_THRESHOLD = 0.65
STABLE_COUNT = 8

PROJECT_ROOT = Path(__file__).resolve().parent
